### ISSUE TITLE
problemas  no capitulo 18  

### ISSUE THREAD

**Issue by edskate** [cursoemvideo/curso-python#17]
tentei baixar os arquivos e baixar o programa para o estudo  mas não consigo precisso de ajuda 
se poder me ajudar ficarei muito feliz  ficarei no aguardo .

**Comment by uezili** [comment]
qual a dificuldade? pode ser mais expecifico?

**Comment by edskate** [comment]
ola  obrigado pela atenção e o jdk pois eu não consigo saber exatamente  o programa certo para instalar 
neste caso e do curso javascript.

**Comment by fisicopeculiar** [comment]
instala o node.js e visual studio code. 
https://nodejs.org/en/
https://code.visualstudio.com/

**Comment by edskate** [comment]
obrigado estou instalando o programa mas se der certo eu respondo se deu certo ok .
